# ==========================================
# APPENDERS CONFIGURATION
# ==========================================

# Console Appender
Appenders.console.type = Console
Appenders.console.name = CONSOLE
Appenders.console.target = SYSTEM_OUT
Appenders.console.PatternLayout.pattern = %d [%t] %p %c - %m%n

# Rolling File Appender
#Appenders.rolling.type = RollingFile
#Appenders.rolling.name = ROLLING_FILE
#Appenders.rolling.fileName = logs/java-current.log
#Appenders.rolling.filePattern = logs/java-%d{yyyy-MM-dd}-%i.log
#Appenders.rolling.PatternLayout.pattern = %d [%t] %p %c - %m%n
#Appenders.rolling.OnStartupTriggeringPolicy.type = OnStartupTriggeringPolicy

# ==========================================
# LOGGERS CONFIGURATION (ROOT)
# ==========================================

Loggers.Root.level = DEBUG

Loggers.Root.AppenderRef.0.ref = CONSOLE
#Loggers.Root.AppenderRef.1.ref = ROLLING_FILE
