name: Enable Automerge
on:
  pull_request:
    branches:
      - main
jobs:
  Enable-Automerge:
    permissions: write-all
    runs-on: ubuntu-latest
    if: ${{ (github.actor == 'dependabot[bot]') || (github.actor == 'tgrothe') }}
    steps:
      - name: Auto Merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
